# Cilium and Gateway API Deployment Module
#
# This module is responsible for deploying Cilium CNI and Gateway API CRDs to the Talos cluster.
# It is designed to be run AFTER the main cluster infrastructure has been provisioned.
#
# Usage:
#   terraform init
#   terraform apply
#
# Prerequisites:
#   - The Talos cluster must be up and running.
#   - A valid kubeconfig file must exist at the path specified by `var.kubeconfig_path`.

terraform {
  cloud {
    organization = "ThorntonCloud"
    workspaces {
      name = "cilium-install"
    }
  }

  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.12"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.24"
    }
    http = {
      source  = "hashicorp/http"
      version = "~> 3.4"
    }
  }
}

# Configure the Helm provider using the kubeconfig generated by the cluster module.
# We use `config_path` instead of inline credentials to avoid race conditions and
# ensure we are using the fully generated config from the previous step.
provider "helm" {
  kubernetes {
    config_path = var.kubeconfig_path
  }
}

# Configure the Kubernetes provider similarly to Helm.
provider "kubernetes" {
  config_path = var.kubeconfig_path
}

# Gateway API CRDs
#
# We fetch the standard Gateway API CRDs directly from the upstream repository.
# This ensures we are using the official definitions for version v1.2.0.
data "http" "gateway_api_crds" {
  for_each = toset([
    "gateway.networking.k8s.io_gatewayclasses.yaml",
    "gateway.networking.k8s.io_gateways.yaml",
    "gateway.networking.k8s.io_httproutes.yaml",
    "gateway.networking.k8s.io_referencegrants.yaml",
    "gateway.networking.k8s.io_grpcroutes.yaml"
  ])
  url = "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/${each.value}"
}

# Apply the Gateway API CRDs to the cluster.
#
# IMPORTANT: We strip the "status" field from the manifests before applying.
# The `kubernetes_manifest` resource does not allow the "status" field because it is
# a computed field managed by the cluster, not the user. Including it causes Terraform errors.
resource "kubernetes_manifest" "gateway_api_crds" {
  for_each = data.http.gateway_api_crds
  manifest = {
    for k, v in yamldecode(each.value.response_body) : k => v
    if k != "status"
  }
}

# Cilium Helm Release
#
# Installs Cilium CNI via Helm.
# This replaces the manual `cilium install` CLI command.
resource "helm_release" "cilium" {
  name       = "cilium"
  repository = "https://helm.cilium.io/"
  chart      = "cilium"
  version    = "1.18.0"
  namespace  = "kube-system"
  
  # Increased timeout to 20 minutes to allow sufficient time for image pulls and startup
  # on slower connections or resource-constrained environments.
  timeout    = 1200

  # Ensure CRDs are installed before Cilium attempts to start, as it may depend on them
  # (especially with gatewayAPI.enabled=true).
  depends_on = [
    kubernetes_manifest.gateway_api_crds
  ]

  # IPAM Mode: Kubernetes
  # Delegates IP address management to Kubernetes.
  set {
    name  = "ipam.mode"
    value = "kubernetes"
  }

  # Kube-Proxy Replacement
  # Cilium replaces kube-proxy for better performance and advanced features.
  set {
    name  = "kubeProxyReplacement"
    value = "true"
  }

  # Security Context Capabilities
  # Required capabilities for Cilium agent to operate in strict environments.
  set {
    name  = "securityContext.capabilities.ciliumAgent"
    value = "{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}"
  }

  set {
    name  = "securityContext.capabilities.cleanCiliumState"
    value = "{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}"
  }

  # CGroup Configuration
  # Talos mounts cgroups at /sys/fs/cgroup, so we disable auto-mount and point to the host root.
  set {
    name  = "cgroup.autoMount.enabled"
    value = "false"
  }

  set {
    name  = "cgroup.hostRoot"
    value = "/sys/fs/cgroup"
  }

  # K8s Service Host
  # Points Cilium to the local API server endpoint (localhost:7445) which is standard for Talos nodes.
  set {
    name  = "k8sServiceHost"
    value = "localhost"
  }

  set {
    name  = "k8sServicePort"
    value = "7445"
  }

  # Gateway API Support
  # Enables Cilium's implementation of the Gateway API.
  set {
    name  = "gatewayAPI.enabled"
    value = "true"
  }

  # Enable ALPN and AppProtocol support for Gateway API
  set {
    name  = "gatewayAPI.enableAlpn"
    value = "true"
  }

  set {
    name  = "gatewayAPI.enableAppProtocol"
    value = "true"
  }
}
