# Cilium and Gateway API Deployment Module
#
# This module is responsible for deploying Cilium CNI and Gateway API CRDs to the Talos cluster.
# It is designed to be run AFTER the main cluster infrastructure has been provisioned.
#
# Usage:
#   terraform init
#   terraform apply
#
# Prerequisites:
#   - The Talos cluster must be up and running.
#   - A valid kubeconfig file must exist at the path specified by `var.kubeconfig_path`.

terraform {
  cloud {
    organization = "ThorntonCloud"
    workspaces {
      name = "cilium-install"
    }
  }

  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 3.0.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.24"
    }
    http = {
      source  = "hashicorp/http"
      version = "~> 3.4"
    }
  }
}

# Configure the Helm provider using the kubeconfig generated by the cluster module.
# We use `config_path` instead of inline credentials to avoid race conditions and
# ensure we are using the fully generated config from the previous step.
provider "helm" {
  kubernetes = {
    config_path = var.kubeconfig_path
  }
}

# Configure the Kubernetes provider similarly to Helm.
provider "kubernetes" {
  config_path = var.kubeconfig_path
}

# Gateway API CRDs
#
# We fetch the standard Gateway API CRDs directly from the upstream repository.
# This ensures we are using the official definitions for version v1.2.0.
data "http" "gateway_api_crds" {
  for_each = toset([
    "gateway.networking.k8s.io_gatewayclasses.yaml",
    "gateway.networking.k8s.io_gateways.yaml",
    "gateway.networking.k8s.io_httproutes.yaml",
    "gateway.networking.k8s.io_referencegrants.yaml",
    "gateway.networking.k8s.io_grpcroutes.yaml"
  ])
  url = "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.2.0/config/crd/standard/${each.value}"
}

# Apply the Gateway API CRDs to the cluster.
#
# IMPORTANT: We strip the "status" field from the manifests before applying.
# The `kubernetes_manifest` resource does not allow the "status" field because it is
# a computed field managed by the cluster, not the user. Including it causes Terraform errors.
resource "kubernetes_manifest" "gateway_api_crds" {
  for_each = data.http.gateway_api_crds
  manifest = {
    for k, v in yamldecode(each.value.response_body) : k => v
    if k != "status"
  }
}

# Cilium Helm Release
#
# Installs Cilium CNI via Helm.
# This replaces the manual `cilium install` CLI command.
resource "helm_release" "cilium" {
  name       = "cilium"
  repository = "https://helm.cilium.io/"
  chart      = "cilium"
  version    = "1.18.0"
  namespace  = "kube-system"

  # Increased timeout to 20 minutes to allow sufficient time for image pulls and startup
  # on slower connections or resource-constrained environments.
  timeout = 1200

  # Ensure CRDs are installed before Cilium attempts to start, as it may depend on them
  # (especially with gatewayAPI.enabled=true).
  depends_on = [
    kubernetes_manifest.gateway_api_crds
  ]

  set = [

    # IPAM Mode: Kubernetes
    # Delegates IP address management to Kubernetes.
    {
      name  = "ipam.mode"
      value = "kubernetes"
    },

    # Kube-Proxy Replacement
    # Cilium replaces kube-proxy for better performance and advanced features.
    {
      name  = "kubeProxyReplacement"
      value = "true"
    },

    # Security Context Capabilities
    # Required capabilities for Cilium agent to operate in strict environments.
    {
      name  = "securityContext.capabilities.ciliumAgent"
      value = "{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}"
    },

    {
      name  = "securityContext.capabilities.cleanCiliumState"
      value = "{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}"
    },

    # CGroup Configuration
    # Talos mounts cgroups at /sys/fs/cgroup, so we disable auto-mount and point to the host root.
    {
      name  = "cgroup.autoMount.enabled"
      value = "false"
    },

    {
      name  = "cgroup.hostRoot"
      value = "/sys/fs/cgroup"
    },

    # K8s Service Host
    # Points Cilium to the local API server endpoint (localhost:7445) which is standard for Talos nodes.
    {
      name  = "k8sServiceHost"
      value = "localhost"
    },

    {
      name  = "k8sServicePort"
      value = "7445"
    },

    # Gateway API Support
    # Enables Cilium's implementation of the Gateway API.
    {
      name  = "gatewayAPI.enabled"
      value = "true"
    },

    # Enable ALPN and AppProtocol support for Gateway API
    {
      name  = "gatewayAPI.enableAlpn"
      value = "true"
    },

    {
      name  = "gatewayAPI.enableAppProtocol"
      value = "true"
    }
  ]


}

# GitHub Actions Runner Controller (ARC)
#
# Installs the ARC controller which manages the lifecycle of runner pods.
resource "helm_release" "arc_controller" {
  name             = "arc"
  repository       = "oci://ghcr.io/actions/actions-runner-controller-charts"
  chart            = "gha-runner-scale-set-controller"
  version          = "0.9.3"
  namespace        = "arc-systems"
  create_namespace = true
}

# ARC Runner Scale Set
#
# Deploys a scale set of runners that connect to the specified GitHub repository/org.
resource "helm_release" "arc_runner_set" {
  name             = var.arc_runner_set_name
  repository       = "oci://ghcr.io/actions/actions-runner-controller-charts"
  chart            = "gha-runner-scale-set"
  version          = "0.9.3"
  namespace        = "arc-runners"
  create_namespace = true

  depends_on = [
    helm_release.arc_controller
  ]

  set = [
    {
      name  = "githubConfigUrl"
      value = var.github_config_url
    },
    {
      name  = "githubConfigSecret.github_token"
      value = var.github_pat
    }
  ]
}
