# Path to the kubeconfig file generated by the main cluster Terraform module.
# This defaults to the standard location where the cluster module writes the file.
variable "kubeconfig_path" {
  description = "Path to the kubeconfig file"
  type        = string
  default     = "../terraform/kubeconfig"
}
