# Path to the kubeconfig file generated by the main cluster Terraform module.
# This defaults to the standard location where the cluster module writes the file.
variable "kubeconfig_path" {
  description = "Path to the kubeconfig file"
  type        = string
  default     = "./kubeconfig"
}

variable "github_config_url" {
  description = "The URL of the GitHub repository or organization for the runner scale set."
  type        = string
}

variable "github_pat" {
  description = "Personal Access Token for GitHub authentication."
  type        = string
  sensitive   = true
}

variable "arc_runner_set_name" {
  description = "Name of the runner scale set."
  type        = string
  default     = "arc-runner-set"
}
