apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: homelab-issuer
spec:
  acme:
    email: jeremy@thorntoncloud.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: homelab-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: jeremyrthor@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token