apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy FIRST
spec:
  project: default
  source:
    repoURL: https://openebs.github.io/charts
    targetRevision: 4.3.2
    chart: openebs
    helm:
      values: |
        mayastor:
          enabled: true
        engines:
          local:
            lvm:
              enabled: true
          replicated:
            mayastor:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true