apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ThorntonCloud/homelab-IaC
    targetRevision: main
    path: applications
    directory:
      recurse: true
      include: '*/app.yaml'
      exclude: 'root-app.yaml'
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true