apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <your-git-repo-url>
    targetRevision: HEAD
    path: infrastructure/envoy-gateway-config/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true